# Local Kafka development environment setup
# ref: https://github.com/simplesteph/kafka-stack-docker-compose/blob/master/full-stack.yml
version: '3'
services:
  redis:
  image: "redis:alpine"
  ports:
    - "6379:6379"
  expose:
  	- 6379
  restart:
  	always
